<?php
/**
 * Standalone Sprint Runner. Context is prepared after authorization.
 *
 * @package SprintEngine
 */

defined( 'ABSPATH' ) || exit;

$sprint_engine_context = get_query_var( 'sprint_engine_runner_context', array() );
if ( ! isset( $sprint_engine_context['state'] ) ) {
	return;
}
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex, nofollow">
	<title><?php echo esc_html( wp_get_document_title() ); ?></title>
	<?php wp_head(); ?>
</head>
<body class="se-runner se-runner--<?php echo esc_attr( $sprint_engine_context['state'] ); ?>">
<?php wp_body_open(); ?>
<a class="se-runner__skip" href="#se-runner-main"><?php esc_html_e( 'Skip to Sprint content', 'sprint-engine' ); ?></a>
<div class="se-runner__shell">
	<nav class="se-runner__utility" aria-label="<?php esc_attr_e( 'Sprint navigation', 'sprint-engine' ); ?>">
		<?php echo \ThePath\SprintEngine\Settings\RunnerBranding::logo(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Core attachment helper escapes markup. ?>
		<?php // Save & Exit retains already-persisted progress; this link performs no save write. ?>
		<a class="se-runner__button se-runner__button--secondary" href="<?php echo esc_url( \ThePath\SprintEngine\Dashboard\Routes::url() ); ?>"><?php echo esc_html( 'in_progress' === $sprint_engine_context['state'] ? __( 'Save & Exit', 'sprint-engine' ) : __( 'Back to My Sprints', 'sprint-engine' ) ); ?></a>
	</nav>
	<header class="se-runner__header">
		<h1><?php echo esc_html( $sprint_engine_context['title'] ?? __( 'Sprint unavailable', 'sprint-engine' ) ); ?></h1>
		<?php if ( isset( $sprint_engine_context['progress'] ) ) : ?>
			<div class="se-runner__progress">
				<p id="se-progress-label">
					<?php
					echo esc_html(
						sprintf(
							/* translators: 1: completed Steps, 2: total Steps, 3: completion percentage. */
							__( '%1$d of %2$d complete — %3$s%%', 'sprint-engine' ),
							$sprint_engine_context['progress']['completed_steps'],
							$sprint_engine_context['progress']['total_steps'],
							number_format_i18n( $sprint_engine_context['progress']['percentage'], 0 )
						)
					);
					?>
				</p>
				<progress max="100" value="<?php echo esc_attr( $sprint_engine_context['progress']['percentage'] ); ?>" aria-labelledby="se-progress-label"><?php echo esc_html( number_format_i18n( $sprint_engine_context['progress']['percentage'], 0 ) ); ?>%</progress>
			</div>
		<?php endif; ?>
	</header>
	<main id="se-runner-main" class="se-runner__main" tabindex="-1">
		<?php echo $sprint_engine_context['featured_image'] ?? ''; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Authorized image generated by core attachment helper. ?>
		<?php if ( 'not_started' === $sprint_engine_context['state'] ) : ?>
			<h2><?php esc_html_e( 'Ready to start', 'sprint-engine' ); ?></h2>
			<p class="se-runner__intro"><?php esc_html_e( 'Take it one Step at a time. You can leave and return as you go.', 'sprint-engine' ); ?></p>
			<?php if ( ! empty( $sprint_engine_context['duration'] ) ) : ?>
				<p>
					<?php
					/* translators: %s: formatted estimated duration. */
					echo esc_html( sprintf( __( 'Estimated time: %s', 'sprint-engine' ), $sprint_engine_context['duration']['label'] ) );
					?>
				</p>
			<?php endif; ?>
			<div class="se-runner__content"><?php echo $sprint_engine_context['overview']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Authorized content rendered through the_content, or escaped excerpt. ?></div>
		<?php elseif ( 'in_progress' === $sprint_engine_context['state'] ) : ?>
			<article aria-labelledby="se-step-title">
				<div class="se-runner__metadata">
					<?php if ( ! empty( $sprint_engine_context['step']['position'] ) ) : ?>
						<span><?php /* translators: 1: current Step position, 2: total Steps. */ echo esc_html( sprintf( __( 'Step %1$d of %2$d', 'sprint-engine' ), $sprint_engine_context['step']['position'], $sprint_engine_context['progress']['total_steps'] ) ); ?></span>
					<?php endif; ?>
					<?php if ( ! empty( $sprint_engine_context['step']['estimated_minutes'] ) ) : ?>
						<span><?php /* translators: %d: estimated minutes. */ echo esc_html( sprintf( _n( 'About %d minute', 'About %d minutes', $sprint_engine_context['step']['estimated_minutes'], 'sprint-engine' ), $sprint_engine_context['step']['estimated_minutes'] ) ); ?></span>
					<?php endif; ?>
				</div>
				<?php if ( $sprint_engine_context['step']['stage'] ) : ?>
					<p class="se-runner__label"><?php echo esc_html( $sprint_engine_context['step']['stage'] ); ?></p>
				<?php endif; ?>
				<h2 id="se-step-title"><?php echo esc_html( $sprint_engine_context['step']['title'] ); ?></h2>
				<?php if ( 'task' === ( $sprint_engine_context['step']['mode'] ?? 'content' ) ) : ?>
					<p class="se-runner__task"><?php esc_html_e( 'Put this into practice before completing this Step.', 'sprint-engine' ); ?></p>
				<?php endif; ?>
				<div class="se-runner__content"><?php echo $sprint_engine_context['step']['content']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Authorized current Step rendered through normal WordPress content filters. ?></div>
			</article>
		<?php elseif ( 'completed' === $sprint_engine_context['state'] ) : ?>
			<div class="se-runner__completion">
				<p class="se-runner__label"><?php esc_html_e( 'All Steps complete', 'sprint-engine' ); ?></p>
				<h2><?php esc_html_e( 'Sprint complete', 'sprint-engine' ); ?></h2>
				<?php $sprint_engine_completion = $sprint_engine_context['completion'] ?? array(); ?>
				<?php echo wpautop( esc_html( '' !== ( $sprint_engine_completion['message'] ?? '' ) ? $sprint_engine_completion['message'] : __( 'You have completed this Sprint. Your progress is saved.', 'sprint-engine' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain text escaped before paragraph formatting. ?>
				<?php if ( '' !== ( $sprint_engine_completion['label'] ?? '' ) && '' !== ( $sprint_engine_completion['url'] ?? '' ) ) : ?>
					<p><a class="se-runner__button se-runner__button--primary" href="<?php echo esc_url( $sprint_engine_completion['url'] ); ?>"><?php echo esc_html( $sprint_engine_completion['label'] ); ?></a></p>
				<?php endif; ?>
				<?php if ( is_user_logged_in() ) : ?>
					<p><button class="se-runner__button se-runner__button--secondary" type="button" id="se-runner-action" aria-describedby="se-runner-status"><?php esc_html_e( 'Restart Sprint', 'sprint-engine' ); ?></button></p>
					<p id="se-runner-status" role="status" aria-live="polite" aria-atomic="true"></p>
					<noscript><p><?php esc_html_e( 'JavaScript is required to restart this Sprint.', 'sprint-engine' ); ?></p></noscript>
				<?php endif; ?>
				<a class="se-runner__button se-runner__button--secondary" href="<?php echo esc_url( \ThePath\SprintEngine\Dashboard\Routes::url() ); ?>"><?php esc_html_e( 'Back to My Sprints', 'sprint-engine' ); ?></a>
			</div>
		<?php else : ?>
			<p class="se-runner__error" role="alert"><?php echo esc_html( $sprint_engine_context['message'] ); ?></p>
		<?php endif; ?>
		<?php if ( is_user_logged_in() && in_array( $sprint_engine_context['state'], array( 'not_started', 'in_progress' ), true ) ) : ?>
			<div class="se-runner__actions">
			<?php if ( 'in_progress' === $sprint_engine_context['state'] ) : ?>
				<p class="se-runner__save-note"><?php esc_html_e( 'Completed Steps are saved. Mark this Step complete when you’re ready.', 'sprint-engine' ); ?></p>
			<?php endif; ?>
			<button class="se-runner__button se-runner__button--primary" type="button" id="se-runner-action" aria-describedby="se-runner-status"><?php echo esc_html( 'not_started' === $sprint_engine_context['state'] ? __( 'Start Sprint', 'sprint-engine' ) : ( ! empty( $sprint_engine_context['step']['is_terminal'] ) ? __( 'Complete Sprint', 'sprint-engine' ) : __( 'Complete & Continue', 'sprint-engine' ) ) ); ?></button>
			<p id="se-runner-status" role="status" aria-live="polite" aria-atomic="true"></p>
			<noscript><p><?php esc_html_e( 'JavaScript is required to start this Sprint and save Step completion in this version.', 'sprint-engine' ); ?></p></noscript>
			</div>
		<?php endif; ?>
	</main>
</div>
<?php wp_footer(); ?>
</body>
</html>
